### ISSUE TITLE
History Skip

### ISSUE THREAD

**Issue by JohnWalkerQ** [bscBot/source#86]
The History Skip does not work. When there is a song that has been in the dj history it does not say anything or warn or skip. I do have the command on enable so i don't know why it does not work.

**Comment by johand199** [comment]
I can not see the problem, works perfectly for me. Have you edited any code?

**Comment by JohnWalkerQ** [comment]
No i havnt edited anything.

**Comment by Benzi** [comment]
I'm closing this for now. If this is still an issue please let me know.
