### ISSUE TITLE
!active do not show the right time

### ISSUE THREAD

**Issue by johand199** [bscBot/source#91]
Here it gives me a random number 
https://gyazo.com/c2b86b77b37e21281a04cde96f776a3f
And on this page it tells us it should show 60min
https://gyazo.com/b7d5adc2a0f5c0c58f595293b49f3858

**Comment by xSidewinderx** [comment]
!active shows how many users chatted in the past X minutes. If no X specified, 60 is set as default.
It doesn't show the bot uptime.

**Comment by xSidewinderx** [comment]
Will be looked into. Just keep an eye out for an update.

**Comment by aalinnfs** [comment]
you need to do !active 60

**Comment by johand199** [comment]
I know that @aalinnfs but as I said; "And on this page it tells us it should show 60min
https://gyazo.com/b7d5adc2a0f5c0c58f595293b49f3858" So if you do not specify the X it should be 60min and it's not. Read the issue better before before you respond please :)
