### ISSUE TITLE
chat messages dissapearing

### ISSUE THREAD

**Issue by BaconGirl** [bscBot/source#93]
On chrome (latest version) after a manager gives some command to the bot, it deletes the previous message on the chat (see image)

![image](https://cloud.githubusercontent.com/assets/6996532/9655550/2e38984a-5232-11e5-8674-dde535680b80.png)

**Comment by xSidewinderx** [comment]
Thats cause of the way plug.dj now groups messages together. So if you have the bot settings to delete commands, this will also group together the last messages sent, unless someone talks in between calling a command and your last chat message. You can toggle command deletion on or off using !commanddeletion

**Comment by johand199** [comment]
Can't be fixed, that's how plug works now. You can request a fix to plug.dj support thought :)
